---
title: "First Lesson October 1rst 2020"
author: IJ
date: '2020-10-05'
categories:
  - Lesson
tags:
  - Lesson
description: ''
thumbnail: ''
---

# First Lesson

Welcome to the first lesson - 05/10/2020 9:00 - 12:00

# Introduction

These Introduction slides present:

*Table of contents*

 1. Introduction
   - Program
   - Motivations
   - Importance of DCM
   - Course Objectives
 2. General Context of Choice analysis
   - Four broad frameworks
   - Sample and Measurement
   - Issues in Model Building
 3. R and Tests for Categorical Data
   - Inference for a (Single) Proportion
   - Two-Way Contingency Tables
   - The Odds-Ratio
   - Chi-Squared Tests of Independence
   
## Zoom meeting

We will use Zoom.

You can connect to zoom:

1. following this link: (https://grenoble-inp.zoom.us/j/96901532282?pwd=b1o4NHVPZE5OQ2xXbTlMQ2o1UTBZQT09)

(and, if needed, install the zoom app).

1. or you can start the Zoom app with the following information
  + meeting ID: 969 0153 2282
  + Password: ECO3

## Class platforms

Depending on the teacher, we will use *Caseine*

I (Iragaël Joly) will try to maintain this blog as a plateform to merge all information and connect to the Caseine and Chamilo plateforms.

 Caseine page is: (https://moodle.caseine.org/course/view.php?id=346)


## Class material

[Introductory Lesson](/Data-pdf/010_Introduction_E3_v2.pdf)

[oddsratio.R](/Data-pdf/oddsratio.R)

[01_Script_Introduction.R](/Data-pdf/01_Script_Introduction.R)